### ISSUE TITLE
Add horizontalToEquatorial method to astropysics.obstools.Site class

### ISSUE THREAD

**Issue by peterjc** [eteq/astropysics#21]
The `equatorialToHorizontal` method looks great, but I want the inverse as well - given local horizontal coordinates (e.g. Altitude/Azimuth from an instrumented telescope), calculate the equatorial coordinates (RA/Dec), based on the site's location and time.

(I saw on @eteq mention on another issue possibly redirecting efforts to astropy, see also https://github.com/astropy/astropy-api/pull/6 about adding similar functionality to astropy)

**Comment by eteq** [comment]
@peterjc - Note that this functionality is now present in [astropy](https://github.com/astropy/astropy) as of v1.0 - see [this example](http://docs.astropy.org/en/v1.0/coordinates/observing-example.html) for how it can be used.  Hence, I'm closing this in astropysics as "will not fix" so as to reduce duplication of effort.

**Comment by peterjc** [comment]
Thank you
